export const NH_ERROR_CODES = [
  'INVALID_PAYLOAD',
  'UNSUPPORTED_CHANNEL',
  'IDEMPOTENCY_CONFLICT',
  'CONSENT_REQUIRED',
  'RISK_CONFIRMATION_REQUIRED',
  'POLICY_BLOCKED',
  'RATE_LIMITED',
  'UPSTREAM_PROVIDER_ERROR',
  'INTERNAL_ERROR'
] as const;

export type NhErrorCode = (typeof NH_ERROR_CODES)[number];
